#!/usr/bin/env lua

-- Reimu - An autotools-like configure program that creates a nob build script

--[[
TODO:
 - dynamic sources from line (like with the cflags)
 - if wget download fails the first time, try again with "--no-check-certificate"
]]--

local cflags = "-Ofast -flto"
local src = '"src/"'
local build = '"build/"'

local function ifexists()
	local nobc = io.open("nob.c", "r")
	if nobc then
		print("Preexisting nob.c exists.")
		print("Deleting...")
		os.remove("nob.c")
		print("Continuing...")
	else
		print("nob.c does not already exist.")
		print("Continuing...")
	end

	local nobh = io.open("nob.h", "r")
	if nobh then
		print("Preexisting nob.h exists.")
		print("Deleting...")
		os.remove("nob.h")
		print("Continuing...")
	else
		print("nob.h does not already exist.")
		print("We will download it in a sec.")
	end
end

local function includes()
	print("Adding basic includes to nob.c...")
	local nob = io.open("nob.c", "a+")
	io.output(nob)
	io.write("// Generated by Reimu by https://github.com/vmunix486\n")
	io.write("#define NOB_IMPLEMENTATION\n")
	io.write('#include "nob.h"\n')
	io.close(nob)
end

local function detect(cmd)
	local status = os.execute(cmd ..  " >/dev/null 2>&1")
	if status == true then 
		-- For whatever reason, the exit code does not follow the normal 0 or 1 scheme, it's either true or false
		return true
	else
		return false
	end
end

local function detectdownloader()
	local wgetstatus = detect("wget")
	if wgetstatus == true then
		print("wget does exist")
		downloader = "wget"
		return
	else
		print("wget does not exist")
	end

	local curlstatus = detect("curl --version") -- For some reason, just running "curl" gives an exit code of 2. --version gives 0.
	if curlstatus == true then
		print("curl does exist")
		downloader = "curl"
		return
	else
		print("curl does not exist")
	end

	print("") -- Red
	print("\27[31mYikes!\27[0m")
	print("\27[31mIt seems like you do not have either wget or curl!\27[0m")
	print("\27[31mYou can download them using your distribution's package manager,\27[0m")
	print("\27[31mor from compiling them from source:\27[0m")
	print("") -- Blue onwards
	print("\27[34mhttps://www.gnu.org/software/wget/\27[0m")
	print("\27[34mhttps://curl.se/\27[0m")
end

local function download()
	if downloader == "wget" then
		print("Downloading the latest nob.h from GitHub with wget...")
		os.execute("wget https://raw.githubusercontent.com/tsoding/nob.h/refs/heads/main/nob.h >/dev/null 2>&1")
		print("Finished downloading. Moving on.")
	end
	-- NOTE: If wget fails, such as using an old verison of wget, certificates, or operating system, then if this command fails,
	-- It should detect that and try and run with --no-check-certificates. We need to add that soon.

	if downloader == "curl" then
		print("Downloading the latest nob.h from GitHub with curl...")
		os.execute("curl -O https://raw.githubusercontent.com/tsoding/nob.h/refs/heads/main/nob.h >/dev/null 2>&1")
		print("Finished downloading. Moving on.")
	end
end

local function detectcompiler()
	local ccstatus = detect("cc --version") -- This is --version for the same reason as curl
	if ccstatus == true then
		print("cc does exist.")
		compiler = "cc"
		return
	else
		print("cc does not exist.")
	end

	-- This is here for filler. This probably does not support running on Windows at all KEKW
	-- !!!AT THE MOMENT!!!
	local clstatus = detect("cl")
	if clstatus == true then
		print("cl does exist.")
		compiler = "cl"
		return
	else
		print("cl does not exist.")
	end

	-- Oooooh fancy schmancy are we?
	print("")
	print("\27[31mYikes!\27[0m")
	print("\27[31mIt seems like you do not have a C compiler installed on your system.\27[0m")
	print("\27[31mIf you have one installed, but it is not set as being an option here, you should either modify the code\27[0m")
	print("\27[31mOr make an issue on the Github.\27[0m")
	print("")
	print("\27[31mIf you just do not have a C compiler... Womp Womp.\27[0m")
end

-- tcflags = tokenize cflags
-- 1500 iq for naming
-- This is probably one of the most absolute bajoding parts of the project
local function tcflags()
	local out = {}

	for flag in string.gmatch(cflags, "%S+") do
		out[#out+1] = '"' .. flag .. '"'
	end

	tcflags = table.concat(out, ", ")
	-- print(tcflags)
end

local function finishnob()
	print("Finishing nob.c...")
        local nob = io.open("nob.c", "a+")
        io.output(nob)
        io.write("\n")
	io.write("#define BUILD_FOLDER " .. build .. "\n")
	io.write("#define SRC_FOLDER " .. src .. "\n")

	io.write("\n")

	io.write("int main(int argc, char **argv)\n")
	io.write("{\n")

	io.write("	NOB_GO_REBUILD_URSELF(argc, argv);\n")
	-- I know this isn't needed with Reimu, but I'm not sure if it's nessisary to have or not.
	io.write("	if (!nob_mkdir_if_not_exists(BUILD_FOLDER)) return 1;\n")
	io.write("	Nob_Cmd cmd = {0};\n")

	-- This is the special mojo sauce line
	-- Get all the sauce you need!
	io.write('	nob_cmd_append(&cmd, "' .. compiler .. '", ' .. tcflags .. ', "-o", BUILD_FOLDER"test", SRC_FOLDER"test.c");\n')
	io.write("	if (!nob_cmd_run(&cmd)) return 1;\n")
	io.write("	return 0;\n")

	io.write("}\n")

        io.close(nob)
end

local function main()
	ifexists()
	includes()
	detectdownloader()
	download()
	detectcompiler()
	tcflags()
	finishnob()
end

main()
