#!/usr/bin/env lua

-- Reimu - An autotools-like configure program that creates a nob build script

local cflags = "-Ofast -flto"
local src = '"src/"'
local build = '"build/"'

--[[
--	Command line argument parsing
--]]
local function parseargs(args)
	local parsed = {}
	for i = 1, #args do
		local arg = args[i]
		local key, value = arg:match("^%-%-([^=]+)=(.+)$") -- I need to look up how this works KEKW
		if key and value then
			parsed[key] = value
		elseif arg:sub(1, 2) == "--" then
			parsed[arg:sub(3)] = true
		else
			table.insert(parsed, arg)
		end
	end
	return parsed
end

local flags = {
	compiler = "cc",
	cflags = "-Ofast -flto",
	downloader = "wget",
	help = "false",
	clean = "false"
}

local args = parseargs(arg)

for k, v in pairs(args) do
	if flags[k] ~= nil then
		flags[k] = v
	end
end

local function help()
	if flags.help == true then
		print("Reimu is a nob configurator in Lua.")
		print("")
		print("Flags:")
		print(" --compiler=[COMMAND]	The command to use as the C compiler command. (default: cc)")
		print(' --cflags=[FLAGS]	The flags to use for the C compiler flags. (default: "-Ofast -flto"')
		print(" --downloader=[COMMAND]	The command to use as the downloader (default: wget)")
		print(" --clean			Cleans out all the files generated. Useful for git commits.")
		print(" --help			Prints this help dialog.")
		os.exit(0)
	end
end

local function clean()
	if flags.clean == true then
		os.execute("rm -rfv nob build/ nob.c nob.h compile.sh")
		os.exit(0)
	end
end

local function flagmain()
	help()
	clean()
end

--[[
--	End Command line argument parsing
--]]

local function ifexists()
	local nobc = io.open("nob.c", "r")
	if nobc then
		print("Preexisting nob.c exists.")
		print("Deleting...")
		os.remove("nob.c")
		print("Continuing...")
	else
		print("nob.c does not already exist.")
		print("Continuing...")
	end

	local nobh = io.open("nob.h", "r")
	if nobh then
		print("Preexisting nob.h exists.")
		print("Deleting...")
		os.remove("nob.h")
		print("Continuing...")
	else
		print("nob.h does not already exist.")
		print("We will download it in a sec.")
	end

	local sh = io.open("compile.sh", "r")
	if sh then
		print("Preexisting compile.sh exists.")
		print("Deleting...")
		os.remove("compile.sh")
		print("Continuing")
	else
		print("compile.sh does not already exist.")
		print("We will download it in a sec.")
	end
end

local function includes()
	print("Adding basic includes to nob.c...")
	local nob = io.open("nob.c", "a+")
	io.output(nob)
	io.write("// Generated by Reimu by https://github.com/vmunix486\n")
	io.write("#define NOB_IMPLEMENTATION\n")
	io.write('#include "nob.h"\n')
	io.close(nob)
end

local function detect(cmd)
	local status = os.execute(cmd ..  " >/dev/null 2>&1")
	if status == true then 
		-- For whatever reason, the exit code does not follow the normal 0 or 1 scheme, it's either true or false
		return true
	else
		return false
	end
end

local function detectdownloader()
	local wgetstatus = detect("wget --version")
	-- If the user is using wget 1.x, then just a plain wget command will give a status code of 1, so use --version
	-- for both wget 1.x and wget2.
	if wgetstatus == true then
		print("wget does exist")
		downloader = "wget"
		return
	else
		print("wget does not exist")
	end

	local curlstatus = detect("curl --version")
	-- For some reason, just running "curl" gives an exit code of 2. --version gives 0.
	if curlstatus == true then
		print("curl does exist")
		downloader = "curl"
		return
	else
		print("curl does not exist")
	end

	print("") -- Red
	print("\27[31mYikes!\27[0m")
	print("\27[31mIt seems like you do not have either wget or curl!\27[0m")
	print("\27[31mYou can download them using your distribution's package manager,\27[0m")
	print("\27[31mor from compiling them from source:\27[0m")
	print("") -- Blue onwards
	print("\27[34mhttps://www.gnu.org/software/wget/\27[0m")
	print("\27[34mhttps://curl.se/\27[0m")
end

local function download()
	if downloader == "wget" then
		print("Downloading the latest nob.h from GitHub with wget...")
		-- July 16, 2026: updated command to use --no-check-certificate so it works on Windows XP
		os.execute("wget https://raw.githubusercontent.com/tsoding/nob.h/refs/heads/main/nob.h --no-check-certificate >/dev/null 2>&1")
		print("Finished downloading. Moving on.")
	end

	if downloader == "curl" then
		print("Downloading the latest nob.h from GitHub with curl...")
		os.execute("curl -O https://raw.githubusercontent.com/tsoding/nob.h/refs/heads/main/nob.h >/dev/null 2>&1")
		print("Finished downloading. Moving on.")
	end
end

local function detectcompiler()
	-- If flags.compiler is not cc, then set the specified compiler as the compiler
	if flags.compiler ~= "cc" then
		compiler = flags.compiler
		return
	end

	local ccstatus = detect("cc --version") -- This is --version for the same reason as curl
	if ccstatus == true then
		print("cc does exist.")
		compiler = "cc"
		return
	else
		print("cc does not exist.")
	end

	-- This is here for filler. This probably does not support running on Windows at all KEKW
	-- !!!AT THE MOMENT!!!
	local clstatus = detect("cl")
	if clstatus == true then
		print("cl does exist.")
		compiler = "cl"
		return
	else
		print("cl does not exist.")
	end

	-- Oooooh fancy schmancy are we?
	print("")
	print("\27[31mYikes!\27[0m")
	print("\27[31mIt seems like you do not have a C compiler installed on your system.\27[0m")
	print("\27[31mIf you have one installed, but it is not set as being an option here, you should either modify the code\27[0m")
	print("\27[31mOr make an issue on the Github.\27[0m")
	print("")
	print("\27[31mIf you just do not have a C compiler... Womp Womp.\27[0m")
end

-- tcflags = tokenize cflags
-- 1500 iq for naming
-- This is probably one of the most absolute bajoding parts of the project
local function tcflags()
	local out = {}

	for flag in string.gmatch(cflags, "%S+") do
		out[#out+1] = '"' .. flag .. '"'
	end

	tcflags = table.concat(out, ", ")
end

local function finishnob()
	print("Finishing nob.c...")
        local nob = io.open("nob.c", "a+")
        io.output(nob)
        io.write("\n")
	io.write("#define BUILD_FOLDER " .. build .. "\n")
	io.write("#define SRC_FOLDER " .. src .. "\n")

	io.write("\n")

	io.write("int main(int argc, char **argv)\n")
	io.write("{\n")

	io.write("	NOB_GO_REBUILD_URSELF(argc, argv);\n")
	-- I know this isn't needed with Reimu, but I'm not sure if it's nessisary to have or not.
	io.write("	if (!nob_mkdir_if_not_exists(BUILD_FOLDER)) return 1;\n")
	io.write("	Nob_Cmd cmd = {0};\n")

	-- This is the special mojo sauce line
	-- Get all the sauce you need!
	io.write('	nob_cmd_append(&cmd, "' .. compiler .. '", ' .. tcflags .. ', "-o", BUILD_FOLDER"test", SRC_FOLDER"test.c");\n')
	io.write("	if (!nob_cmd_run(&cmd)) return 1;\n")
	io.write("	return 0;\n")

	io.write("}\n")

        io.close(nob)
end

local function shscript()
	print("Creating compile.sh")
	local sh = io.open("compile.sh", "a+")
	io.output(sh)
	io.write("#!/bin/sh\n")
	io.write("\n# Generated by Reimu by vmunix. https://github.com/vmunix486\n")
	io.write(compiler .. " -o nob nob.c && ./nob\n")
	io.close(sh)
	os.execute("chmod +x ./compile.sh")
end

local function main()
	flagmain()
	ifexists()
	includes()
	detectdownloader()
	download()
	detectcompiler()
	tcflags()
	finishnob()
	shscript()
end

main()
